import { unzipSync, strFromU8 } from "fflate";
import type { VaultImportSheet } from "../types/vault";

const MAX_FILE_BYTES = 5 * 1024 * 1024; const MAX_SHEETS = 20; const MAX_ROWS = 2_000; const MAX_COLUMNS = 80; const MAX_CELL_LENGTH = 4_000;
const clean = (value: unknown) => String(value ?? "").replace(/\0/g, "").trim().slice(0, MAX_CELL_LENGTH);
const csvRows = (text: string) => { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (quoted && char === '"' && text[i + 1] === '"') { cell += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && char === ",") { row.push(cell); cell = ""; } else if (!quoted && (char === "\n" || char === "\r")) { if (char === "\r" && text[i + 1] === "\n") i += 1; row.push(cell); if (row.some((item) => item.trim())) rows.push(row); row = []; cell = ""; } else cell += char; } row.push(cell); if (row.some((item) => item.trim())) rows.push(row); return rows; };
const normalHeaders = (cells: string[]) => { const used = new Map<string, number>(); return cells.slice(0, MAX_COLUMNS).map((value, index) => { const base = clean(value) || `Column ${index + 1}`; const count = (used.get(base.toLowerCase()) || 0) + 1; used.set(base.toLowerCase(), count); return count === 1 ? base : `${base} (${count})`; }); };
const toSheet = (category: string, matrix: string[][]): VaultImportSheet | null => { const meaningful = matrix.filter((row) => row.some((cell) => clean(cell))); if (meaningful.length < 2) return null; const headers = normalHeaders(meaningful[0]); const rows = meaningful.slice(1, MAX_ROWS + 1).map((row) => Object.fromEntries(headers.map((header, index) => [header, clean(row[index])]))).filter((row) => Object.values(row).some(Boolean)); return rows.length ? { category: clean(category) || "Imported records", headers, rows } : null; };
const colIndex = (ref: string) => ref.replace(/\d/g, "").split("").reduce((sum, char) => sum * 26 + char.charCodeAt(0) - 64, 0) - 1;
const xmlDecode = (value: string) => value.replace(/&(?:amp|lt|gt|quot|apos);/g, (entity) => ({ "&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": '"', "&apos;": "'" }[entity] || entity)).replace(/&#(x[\da-f]+|\d+);/gi, (_, code) => String.fromCodePoint(String(code).toLowerCase().startsWith("x") ? parseInt(String(code).slice(1), 16) : parseInt(String(code), 10)));
const attr = (tag: string, name: string) => tag.match(new RegExp(`(?:^|\\s)${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}="([^"]*)"`))?.[1] || "";
const tagText = (xml: string, tag: string) => [...xml.matchAll(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`, "g"))].map((match) => xmlDecode(match[1].replace(/<[^>]+>/g, ""))).join("");
function xlsxSheets(bytes: Uint8Array): VaultImportSheet[] { const files = unzipSync(bytes); const text = (name: string) => files[name] ? strFromU8(files[name]) : ""; if (Object.keys(files).some((name) => /vbaProject\.bin$/i.test(name))) throw new Error("Macro-enabled workbooks are not supported."); const shared = [...text("xl/sharedStrings.xml").matchAll(/<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)].map((item) => tagText(item[1], "t")); const workbook = text("xl/workbook.xml"); const relations = text("xl/_rels/workbook.xml.rels"); if (!workbook || !relations) throw new Error("This .xlsx file is missing workbook data."); const targets = new Map([...relations.matchAll(/<Relationship\s+([^>]*?)\/?>(?:<\/Relationship>)?/g)].map((item) => [attr(item[1], "Id"), `xl/${attr(item[1], "Target").replace(/^\//, "")}`])); const sheets = [...workbook.matchAll(/<sheet\s+([^>]*?)\/?>(?:<\/sheet>)?/g)].slice(0, MAX_SHEETS); const parsed = sheets.flatMap((sheet) => { const name = xmlDecode(attr(sheet[1], "name")) || "Imported records"; const path = targets.get(attr(sheet[1], "r:id")); if (!path || !files[path]) return []; const document = text(path); if (/<f(?:\s[^>]*)?>/i.test(document)) throw new Error("Formula cells are not supported. Export values-only, then import."); const matrix = [...document.matchAll(/<row(?:\s[^>]*)?>([\s\S]*?)<\/row>/g)].map((row) => { const result: string[] = []; [...row[1].matchAll(/<c\s+([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)].forEach((cell) => { const index = colIndex(attr(cell[1], "r") || "A1"); const type = attr(cell[1], "t"); const body = cell[2] || ""; const value = type === "inlineStr" ? tagText(body, "t") : tagText(body, "v"); result[index] = type === "s" ? shared[Number(value)] || "" : value; }); return result; }); const result = toSheet(name, matrix); return result ? [result] : []; }); if (!parsed.length) throw new Error("No data rows were found. Ensure the first row contains headers and the next row contains data."); return parsed; }
export async function parseVaultImportFile(file: File): Promise<VaultImportSheet[]> { if (file.size > MAX_FILE_BYTES) throw new Error("Import files must be 5 MB or smaller."); const name = file.name.toLowerCase(); if (name.endsWith(".csv")) { const sheet = toSheet(file.name.replace(/\.csv$/i, ""), csvRows(await file.text())); return sheet ? [sheet] : []; } if (name.endsWith(".xlsx")) return xlsxSheets(new Uint8Array(await file.arrayBuffer())); throw new Error("Use a CSV or .xlsx file. Legacy .xls files are not supported safely."); }
