import { Check, Clock3, Plus, SkipForward, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { logRoutine, saveRoutine } from "../lib/routine-service";
import { localDateKey } from "../lib/project-schedule";
import type { Routine, RoutineCategory, RoutineLog } from "../types/tracker";
type Props = { uid: string; routines: Routine[]; logs: RoutineLog[] };
const categories: RoutineCategory[] = ["spiritual", "health", "break", "personal"];
export default function DisciplineView({ uid, routines, logs }: Props) { const [adding, setAdding] = useState(false); const today = localDateKey(); const todayDay = new Date(`${today}T12:00:00`).getDay(); const todays = useMemo(() => routines.filter(r => r.active && r.repeatDays.includes(todayDay)), [routines, todayDay]); const record = (id: string) => logs.find(l => l.id === `${id}-${today}`); const complete = (r: Routine, status: "completed" | "skipped") => void logRoutine(uid, r.id, today, status); return <main className="discipline-page"><header><div><span className="discipline-icon"><Sparkles size={21}/></span><div><h1>Discipline</h1><p>Keep your personal commitments alongside focused work.</p></div></div><button className="start-btn" onClick={() => setAdding(true)}><Plus size={16}/> New routine</button></header><section className="discipline-summary"><article><span>Today’s routines</span><b>{todays.length}</b></article><article><span>Completed</span><b>{todays.filter(r => record(r.id)?.status === "completed").length} / {todays.length}</b></article><article><span>Consistency</span><b>{todays.length ? Math.round(todays.filter(r => record(r.id)?.status === "completed").length / todays.length * 100) : 0}%</b></article></section><section className="discipline-timeline"><header><div><span className="eyebrow">TODAY’S ROUTINE</span><h2>{new Date(`${today}T12:00:00`).toLocaleDateString("en-GB", { weekday:"long", day:"numeric", month:"long" })}</h2></div><span>{todays.filter(r => !record(r.id)).length} remaining</span></header>{todays.length ? todays.map(r => { const state = record(r.id)?.status; return <article key={r.id} className={state || "planned"}><time>{r.time}</time><i className={r.category}/><div><b>{r.name}</b><small>{r.category} · {r.durationMinutes} min · {r.sessionBehavior === "pause" ? "Auto-pause work session" : "Reminder only"}</small></div>{state ? <em>{state}</em> : <div className="routine-actions"><button onClick={() => complete(r,"completed")}><Check size={15}/> Complete</button><button onClick={() => complete(r,"skipped")}><SkipForward size={15}/> Skip</button></div>}</article> }) : <p className="discipline-empty">No routines planned today. Create one to start building your schedule.</p>}</section>{adding && <RoutineModal onClose={() => setAdding(false)} onSave={async input => { await saveRoutine(uid, input); setAdding(false); }}/>}</main>; }
function RoutineModal({ onClose, onSave }: { onClose: () => void; onSave: (input: Omit<Routine,"id"|"createdAt"|"updatedAt">) => Promise<void> }) { const [busy,setBusy]=useState(false); return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => {e.preventDefault(); const f=new FormData(e.currentTarget); setBusy(true); try { await onSave({name:String(f.get("name")),category:String(f.get("category")) as RoutineCategory,time:String(f.get("time")),durationMinutes:Number(f.get("duration")),repeatDays:[0,1,2,3,4,5,6],reminderMinutes:Number(f.get("reminder")),sessionBehavior:String(f.get("behavior")) as "warn"|"pause",strict:f.get("strict")==="on",active:true});}finally{setBusy(false)}}}><button className="modal-close" type="button" onClick={onClose}>×</button><div className="modal-icon"><Clock3 size={20}/></div><h3>New routine</h3><label className="modal-field">ROUTINE NAME<input name="name" required placeholder="Lunch, Namaz, Sleep…"/></label><label className="modal-field">CATEGORY<select name="category">{categories.map(c=><option key={c}>{c}</option>)}</select></label><div className="routine-form-grid"><label className="modal-field">TIME<input name="time" type="time" defaultValue="13:00" required/></label><label className="modal-field">DURATION (MIN)<input name="duration" type="number" min="1" defaultValue="15" required/></label></div><label className="modal-field">ACTIVE SESSION<select name="behavior"><option value="pause">Automatically pause work</option><option value="warn">Reminder only</option></select></label><label className="modal-field">REMIND ME<input name="reminder" type="number" min="0" defaultValue="5" required/></label><label className="note-pin"><input name="strict" type="checkbox"/> Strict mode inside EA Log</label><div className="modal-actions"><button className="outline-btn" type="button" onClick={onClose}>Cancel</button><button className="start-btn" disabled={busy}>{busy?"Saving…":"Save routine"}</button></div></form></div>; }
