import { Archive, CircleDollarSign, Landmark, Plus, Repeat2, RotateCcw, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import type { FinanceAccount, FinanceAccountKind, FinanceAsset, FinanceBudget, FinanceGoal, FinanceTransaction, Project, RecurringFinanceItem } from "../types/tracker";

type Props = { accounts: FinanceAccount[]; transactions: FinanceTransaction[]; assets: FinanceAsset[]; goals: FinanceGoal[]; recurring: RecurringFinanceItem[]; budgets: FinanceBudget[]; projects: Project[]; workLogs: { projectId: string; durationMinutes?: number }[]; onAccount: (x: Omit<FinanceAccount, "id" | "createdAt">) => Promise<void>; onArchiveAccount: (id: string) => Promise<void>; onRestoreAccount: (id: string) => Promise<void>; onTransaction: (x: Omit<FinanceTransaction, "id" | "createdAt">) => Promise<void>; onReverse: (x: FinanceTransaction) => Promise<void>; onAsset: (x: Omit<FinanceAsset, "id" | "createdAt">) => Promise<void>; onGoal: (x: Omit<FinanceGoal, "id" | "createdAt">) => Promise<void>; onRecurring: (x: Omit<RecurringFinanceItem, "id" | "createdAt">) => Promise<void>; onPostRecurring: (x: RecurringFinanceItem) => Promise<void>; onBudget: (x: Omit<FinanceBudget, "id" | "createdAt">) => Promise<void> };
type Tab = "overview" | "transactions" | "accounts" | "personal" | "business" | "wealth";
const money = (n: number) => new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT", maximumFractionDigits: 0 }).format(n);
const total = (rows: FinanceTransaction[], type: FinanceTransaction["type"]) => rows.filter(row => row.type === type).reduce((sum, row) => sum + row.amount, 0);

export default function FinanceView(props: Props) {
  const { accounts, transactions, assets, goals, recurring, budgets, projects, workLogs } = props;
  const [tab, setTab] = useState<Tab>("overview");
  const [modal, setModal] = useState<"account" | "transaction" | "asset" | "goal" | "recurring" | "budget" | null>(null);
  const [period, setPeriod] = useState(new Date().toLocaleDateString("en-CA").slice(0, 7));
  const activeAccounts = accounts.filter(account => !account.archived);
  const balances = useMemo(() => Object.fromEntries(accounts.map(account => [account.id, account.openingBalance + transactions.reduce((sum, row) => sum + (row.accountId === account.id ? (row.type === "expense" || row.type === "transfer" ? -row.amount : row.amount) : 0) + (row.toAccountId === account.id ? row.amount : 0), 0)])), [accounts, transactions]);
  const current = transactions.filter(row => row.date.startsWith(period));
  const personal = current.filter(row => row.scope === "personal"), business = current.filter(row => row.scope === "business");
  const income = total(current, "income"), expense = total(current, "expense");
  const personalIncome = total(personal, "income"), personalExpense = total(personal, "expense");
  const businessIncome = total(business, "income"), businessExpense = total(business, "expense");
  const cash = activeAccounts.filter(account => account.kind !== "liability").reduce((sum, account) => sum + (balances[account.id] || 0), 0);
  const debt = activeAccounts.filter(account => account.kind === "liability").reduce((sum, account) => sum + (balances[account.id] || 0), 0);
  const manualAssets = assets.filter(asset => asset.type === "asset").reduce((sum, asset) => sum + asset.value, 0);
  const manualDebt = assets.filter(asset => asset.type === "liability").reduce((sum, asset) => sum + asset.value, 0);
  const categories = [...new Set(personal.filter(row => row.type === "expense").map(row => row.category))].map(category => ({ category, amount: personal.filter(row => row.type === "expense" && row.category === category).reduce((sum, row) => sum + row.amount, 0) })).sort((a, b) => b.amount - a.amount);
  const reverse = async (row: FinanceTransaction) => { if (confirm(`Create a correcting reversal for “${row.description || row.category}”? The original remains in history.`)) await props.onReverse(row); };
  return <section className="finance-page"><header className="finance-header"><div><span className="finance-icon"><Landmark size={21} /></span><div><h1>Finance</h1><p>Personal and business money, kept separate and clear.</p></div></div><div className="finance-header-actions"><label>Period<input type="month" value={period} onChange={event => setPeriod(event.target.value)} /></label><button className="start-btn" onClick={() => setModal("transaction")}><Plus size={16} /> Add transaction</button></div></header><div className="finance-tabs">{(["overview", "transactions", "accounts", "personal", "business", "wealth"] as Tab[]).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "overview" && <><section className="finance-kpis"><Kpi label="Cash position" value={money(cash)} /><Kpi label={`${period} income`} value={money(income)} tone="green" /><Kpi label={`${period} expenses`} value={money(expense)} tone="red" /><Kpi label="Net cash flow" value={money(income - expense)} tone={income >= expense ? "green" : "red"} /></section><section className="finance-scope-grid"><Scope title="Business" income={businessIncome} expense={businessExpense} result="Profit" /><Scope title="Personal" income={personalIncome} expense={personalExpense} result="Saved" /></section><ProjectPerformance projects={projects} transactions={business} workLogs={workLogs} /></>}
    {tab === "transactions" && <section className="finance-panel"><div className="finance-section-head"><div><h3>Transactions</h3><p>Use reversal to correct an entry. History remains intact.</p></div><button className="outline-btn" onClick={() => setModal("recurring")}><Repeat2 size={15} /> Recurring</button></div>{transactions.filter(row => row.date.startsWith(period)).map(row => <article className="finance-row" key={row.id}><i className={row.type} /><div><b>{row.description || row.category}</b><small>{row.date} · {row.scope}{row.projectId ? ` · ${projects.find(project => project.id === row.projectId)?.name || "Project"}` : ""}{row.reversalOf ? " · correction" : ""}</small></div><strong className={row.type}>{row.type === "expense" ? "−" : row.type === "income" ? "+" : "↔"}{money(row.amount)}</strong>{!row.reversalOf && <button className="finance-action" title="Reverse transaction" onClick={() => void reverse(row)}><RotateCcw size={15} /></button>}</article>)} {!transactions.filter(row => row.date.startsWith(period)).length && <p>No transactions for this period.</p>} {recurring.length > 0 && <div className="finance-recurring"><h4>Recurring plan</h4>{recurring.filter(item => item.active).map(item => <div key={item.id}><small>{item.type} · {money(item.amount)} · day {item.dayOfMonth} · {item.category}</small><button className="outline-btn" onClick={() => void props.onPostRecurring(item)}>Post now</button></div>)}</div>}</section>}
    {tab === "accounts" && <section className="finance-panel"><div className="finance-section-head"><h3>Accounts</h3><button className="outline-btn" onClick={() => setModal("account")}><Plus size={15} /> New account</button></div>{accounts.map(account => <article className={`finance-row ${account.archived ? "archived" : ""}`} key={account.id}><WalletCards size={18} /><div><b>{account.name}</b><small>{account.kind === "cash" ? "Cash & Bank" : account.kind}{account.archived ? " · archived" : ""}</small></div><strong>{money(balances[account.id] || 0)}</strong><button className="finance-action" title={account.archived ? "Restore account" : "Archive account"} onClick={() => void (account.archived ? props.onRestoreAccount(account.id) : props.onArchiveAccount(account.id))}>{account.archived ? <RotateCcw size={15} /> : <Archive size={15} />}</button></article>)}</section>}
    {tab === "personal" && <><section className="finance-kpis"><Kpi label="Personal income" value={money(personalIncome)} tone="green" /><Kpi label="Spending" value={money(personalExpense)} tone="red" /><Kpi label="Saved" value={money(personalIncome - personalExpense)} tone="green" /><Kpi label="Savings rate" value={personalIncome ? `${Math.round((personalIncome - personalExpense) / personalIncome * 100)}%` : "—"} /></section><section className="finance-panel"><div className="finance-section-head"><h3>Spending by category</h3><div><button className="outline-btn" onClick={() => setModal("budget")}>Budget</button> <button className="outline-btn" onClick={() => setModal("goal")}><Plus size={15} /> Savings goal</button></div></div>{categories.map(item => <div className="finance-category" key={item.category}><b>{item.category}</b><span><i style={{ width: `${Math.min(100, item.amount / Math.max(1, personalExpense) * 100)}%` }} /></span><strong>{money(item.amount)}</strong></div>)}{!categories.length && <p>Add personal expenses with categories to see this analytics.</p>}<Budgets items={budgets.filter(item => item.month === period)} actual={personal} /><Goals goals={goals} accounts={accounts} balances={balances} /></section></>}
    {tab === "business" && <><section className="finance-kpis"><Kpi label="Revenue" value={money(businessIncome)} tone="green" /><Kpi label="Business costs" value={money(businessExpense)} tone="red" /><Kpi label="Profit" value={money(businessIncome - businessExpense)} tone="green" /><Kpi label="Margin" value={businessIncome ? `${Math.round((businessIncome - businessExpense) / businessIncome * 100)}%` : "—"} /></section><ProjectPerformance projects={projects} transactions={business} workLogs={workLogs} /><section className="finance-panel"><h3>Business overhead</h3><p>{money(business.filter(row => !row.projectId && row.type === "expense").reduce((sum, row) => sum + row.amount, 0))} unlinked business expenses. Only project-linked entries contribute to a project’s P&L.</p></section></>}
    {tab === "wealth" && <><section className="finance-kpis"><Kpi label="Total assets" value={money(cash + manualAssets)} tone="green" /><Kpi label="Liabilities" value={money(debt + manualDebt)} tone="red" /><Kpi label="Net worth" value={money(cash + manualAssets - debt - manualDebt)} tone="green" /><Kpi label="Investments" value={money(activeAccounts.filter(account => account.kind === "investment").reduce((sum, account) => sum + (balances[account.id] || 0), 0))} /></section><section className="finance-panel"><div className="finance-section-head"><h3>Assets & liabilities</h3><button className="outline-btn" onClick={() => setModal("asset")}><Plus size={15} /> Add value</button></div>{assets.map(asset => <article className="finance-row" key={asset.id}><CircleDollarSign size={18} /><div><b>{asset.name}</b><small>{asset.type}{asset.note ? ` · ${asset.note}` : ""}</small></div><strong className={asset.type === "asset" ? "income" : "expense"}>{money(asset.value)}</strong></article>)}{!assets.length && <p>Add vehicle, property, or a liability not represented by an account.</p>}</section></>}
    {modal === "account" && <AccountModal onClose={() => setModal(null)} onSave={async value => { await props.onAccount(value); setModal(null); }} />}{modal === "transaction" && <TransactionModal accounts={activeAccounts} projects={projects} onClose={() => setModal(null)} onSave={async value => { await props.onTransaction(value); setModal(null); }} />}{modal === "asset" && <AssetModal onClose={() => setModal(null)} onSave={async value => { await props.onAsset(value); setModal(null); }} />}{modal === "goal" && <GoalModal accounts={activeAccounts} onClose={() => setModal(null)} onSave={async value => { await props.onGoal(value); setModal(null); }} />}{modal === "recurring" && <RecurringModal accounts={activeAccounts} projects={projects} onClose={() => setModal(null)} onSave={async value => { await props.onRecurring(value); setModal(null); }} />}{modal === "budget" && <BudgetModal month={period} onClose={() => setModal(null)} onSave={async value => { await props.onBudget(value); setModal(null); }} />}
  </section>;
}

function Kpi({ label, value, tone = "" }: { label: string; value: string; tone?: string }) { return <article className={`finance-kpi ${tone}`}><small>{label}</small><b>{value}</b></article>; }
function Scope({ title, income, expense, result }: { title: string; income: number; expense: number; result: string }) { return <section className="finance-panel finance-scope"><h3>{title}</h3><div><span>Income <b>{money(income)}</b></span><span>Expense <b>{money(expense)}</b></span><strong>{result} {money(income - expense)}</strong></div></section>; }
function ProjectPerformance({ projects, transactions, workLogs }: { projects: Project[]; transactions: FinanceTransaction[]; workLogs: { projectId: string; durationMinutes?: number }[] }) { return <section className="finance-panel"><h3>Project performance</h3>{projects.map(project => { const rows = transactions.filter(row => row.projectId === project.id), revenue = total(rows, "income"), expense = total(rows, "expense"), profit = revenue - expense, minutes = workLogs.filter(log => log.projectId === project.id).reduce((sum, log) => sum + (log.durationMinutes || 0), 0); return <div className="finance-project" key={project.id}><b>{project.name}</b><span>Revenue {money(revenue)}</span><span>Expense {money(expense)}</span><strong>{money(profit)}{revenue ? <small> · {Math.round(profit / revenue * 100)}%</small> : ""}</strong>{minutes > 0 && <em>Profit/hr {money(profit / (minutes / 60))}</em>}</div>; })}</section>; }
function Budgets({ items, actual }: { items: FinanceBudget[]; actual: FinanceTransaction[] }) { return items.length ? <div className="finance-budgets"><h4>Budgets</h4>{items.map(item => { const spent = actual.filter(row => row.type === "expense" && row.category === item.category && row.scope === item.scope).reduce((sum, row) => sum + row.amount, 0); return <div key={item.id}><b>{item.category}</b><span><i style={{ width: `${Math.min(100, spent / item.limitAmount * 100)}%` }} /></span><small>{money(spent)} / {money(item.limitAmount)}</small></div>; })}</div> : null; }
function Goals({ goals, accounts, balances }: { goals: FinanceGoal[]; accounts: FinanceAccount[]; balances: Record<string, number> }) { return goals.length ? <div className="finance-goals">{goals.map(goal => { const current = goal.accountId ? balances[goal.accountId] || 0 : accounts.filter(account => account.kind === "savings").reduce((sum, account) => sum + (balances[account.id] || 0), 0); return <div key={goal.id}><b>{goal.name}</b><span><i style={{ width: `${Math.min(100, current / goal.targetAmount * 100)}%` }} /></span><small>{money(current)} / {money(goal.targetAmount)}</small></div>; })}</div> : null; }
function Actions({ onClose, label, disabled = false }: { onClose: () => void; label: string; disabled?: boolean }) { return <div className="modal-actions"><button type="button" className="outline-btn" onClick={onClose}>Cancel</button><button className="start-btn" disabled={disabled}>{label}</button></div>; }
function AccountModal({ onClose, onSave }: { onClose: () => void; onSave: (x: Omit<FinanceAccount, "id" | "createdAt">) => Promise<void> }) { return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ name: String(f.get("name")).trim(), kind: String(f.get("kind")) as FinanceAccountKind, openingBalance: Number(f.get("opening") || 0), archived: false }); }}><h3>New account</h3><label className="modal-field">NAME<input name="name" required /></label><label className="modal-field">FINANCIAL ROLE<select name="kind"><option value="cash">Cash & Bank</option><option value="savings">Savings</option><option value="investment">Investment</option><option value="liability">Liability / loan</option></select></label><label className="modal-field">OPENING BALANCE<input name="opening" type="number" min="0" step="0.01" defaultValue="0" /></label><Actions onClose={onClose} label="Save account" /></form></div>; }
function TransactionModal({ accounts, projects, onClose, onSave }: { accounts: FinanceAccount[]; projects: Project[]; onClose: () => void; onSave: (x: Omit<FinanceTransaction, "id" | "createdAt">) => Promise<void> }) { const [type, setType] = useState<FinanceTransaction["type"]>("expense"); return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ type, amount: Number(f.get("amount")), accountId: String(f.get("account")), toAccountId: type === "transfer" ? String(f.get("toAccount")) : null, category: String(f.get("category")).trim(), scope: String(f.get("scope")) as "personal" | "business", projectId: String(f.get("project") || "") || null, date: String(f.get("date")), description: String(f.get("description")).trim(), reversalOf: null }); }}><h3>Add transaction</h3><div className="routine-form-grid"><label className="modal-field">TYPE<select value={type} onChange={e => setType(e.target.value as FinanceTransaction["type"])}><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select></label><label className="modal-field">AMOUNT<input name="amount" type="number" min="0.01" step="0.01" required /></label></div><label className="modal-field">ACCOUNT<select name="account">{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{type === "transfer" && <label className="modal-field">TO ACCOUNT<select name="toAccount">{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<div className="routine-form-grid"><label className="modal-field">SCOPE<select name="scope"><option value="personal">Personal</option><option value="business">Business</option></select></label><label className="modal-field">PROJECT<select name="project"><option value="">No project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><label className="modal-field">CATEGORY<input name="category" required placeholder="Food, client payment, hosting…" /></label><label className="modal-field">DATE<input name="date" type="date" defaultValue={new Date().toLocaleDateString("en-CA")} required /></label><label className="modal-field">DESCRIPTION<input name="description" /></label><Actions onClose={onClose} label={accounts.length ? "Save transaction" : "Create an account first"} disabled={!accounts.length} /></form></div>; }
function AssetModal({ onClose, onSave }: { onClose: () => void; onSave: (x: Omit<FinanceAsset, "id" | "createdAt">) => Promise<void> }) { return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ name: String(f.get("name")).trim(), type: String(f.get("type")) as "asset" | "liability", value: Number(f.get("value")), note: String(f.get("note")).trim() }); }}><h3>Asset or liability</h3><label className="modal-field">NAME<input name="name" required /></label><label className="modal-field">TYPE<select name="type"><option value="asset">Asset</option><option value="liability">Liability</option></select></label><label className="modal-field">CURRENT VALUE<input name="value" type="number" min="0.01" required /></label><label className="modal-field">NOTE<input name="note" /></label><Actions onClose={onClose} label="Save value" /></form></div>; }
function GoalModal({ accounts, onClose, onSave }: { accounts: FinanceAccount[]; onClose: () => void; onSave: (x: Omit<FinanceGoal, "id" | "createdAt">) => Promise<void> }) { return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ name: String(f.get("name")).trim(), targetAmount: Number(f.get("target")), accountId: String(f.get("account") || "") || null }); }}><h3>Savings goal</h3><label className="modal-field">GOAL<input name="name" required /></label><label className="modal-field">TARGET AMOUNT<input name="target" type="number" min="1" required /></label><label className="modal-field">LINKED SAVINGS ACCOUNT<select name="account"><option value="">All savings accounts</option>{accounts.filter(a => a.kind === "savings").map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><Actions onClose={onClose} label="Save goal" /></form></div>; }
function BudgetModal({ month, onClose, onSave }: { month: string; onClose: () => void; onSave: (x: Omit<FinanceBudget, "id" | "createdAt">) => Promise<void> }) { return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ month, category: String(f.get("category")).trim(), scope: String(f.get("scope")) as "personal" | "business", limitAmount: Number(f.get("limit")) }); }}><h3>Monthly budget</h3><p>Sets a spending limit for {month}. It does not block transactions.</p><label className="modal-field">CATEGORY<input name="category" required placeholder="Food, transport, hosting…" /></label><label className="modal-field">SCOPE<select name="scope"><option value="personal">Personal</option><option value="business">Business</option></select></label><label className="modal-field">LIMIT<input name="limit" type="number" min="1" required /></label><Actions onClose={onClose} label="Save budget" /></form></div>; }
function RecurringModal({ accounts, projects, onClose, onSave }: { accounts: FinanceAccount[]; projects: Project[]; onClose: () => void; onSave: (x: Omit<RecurringFinanceItem, "id" | "createdAt">) => Promise<void> }) { return <div className="modal-backdrop"><form className="note-modal" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await onSave({ type: String(f.get("type")) as FinanceTransaction["type"], amount: Number(f.get("amount")), accountId: String(f.get("account")), category: String(f.get("category")), scope: String(f.get("scope")) as "personal" | "business", projectId: String(f.get("project") || "") || null, description: String(f.get("description")), dayOfMonth: Number(f.get("day")), active: true }); }}><h3>Recurring plan</h3><p>This is a monthly template/reminder. It never creates a transaction silently.</p><label className="modal-field">TYPE<select name="type"><option value="expense">Expense</option><option value="income">Income</option></select></label><label className="modal-field">AMOUNT<input name="amount" type="number" min="0.01" required /></label><label className="modal-field">ACCOUNT<select name="account">{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="routine-form-grid"><label className="modal-field">SCOPE<select name="scope"><option value="personal">Personal</option><option value="business">Business</option></select></label><label className="modal-field">DAY<input name="day" type="number" min="1" max="28" defaultValue="1" /></label></div><label className="modal-field">PROJECT<select name="project"><option value="">No project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="modal-field">CATEGORY<input name="category" required /></label><label className="modal-field">DESCRIPTION<input name="description" /></label><Actions onClose={onClose} label="Save plan" /></form></div>; }
