import { Archive, CheckSquare, FileText, MessageSquare, MoreHorizontal, Pin, Plus, Search, Star, StickyNote, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import type { NoteType, Project, ProjectNote, TodoPriority } from "../types/tracker";

type Props = {
  notes: ProjectNote[]; projects: Project[]; initialProjectId?: string | null;
  onCreate: (input: { projectId: string; title: string; content: string; type: NoteType; pinned: boolean }) => Promise<void>;
  onUpdate: (note: ProjectNote, patch: Partial<Pick<ProjectNote, "title" | "content" | "type" | "pinned" | "state">>) => Promise<void>;
  onDelete: (note: ProjectNote) => Promise<void>;
  onConvert: (note: ProjectNote, input: { title: string; priority: TodoPriority; plannedDateString: string }) => Promise<void>;
};
const types: { value: NoteType | "all" | "pinned"; label: string }[] = [
  { value: "all", label: "All" }, { value: "pinned", label: "Pinned" }, { value: "important", label: "Important" }, { value: "message", label: "Messages" }, { value: "information", label: "Information" }, { value: "status", label: "Status" },
];
export default function NotesView({ notes, projects, initialProjectId, onCreate, onUpdate, onDelete, onConvert }: Props) {
  const [projectId, setProjectId] = useState(initialProjectId || "all");
  const [filter, setFilter] = useState<NoteType | "all" | "pinned">("all");
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<ProjectNote | null>(null);
  const [creating, setCreating] = useState(false);
  const [converting, setConverting] = useState<ProjectNote | null>(null);
  const projectFor = (id: string) => projects.find((project) => project.id === id);
  const visible = useMemo(() => notes.filter((note) => note.state === "active" && (projectId === "all" || note.projectId === projectId) && (filter === "all" || filter === "pinned" ? !filter || !note.pinned ? filter !== "pinned" : true : note.type === filter) && `${note.title} ${note.content} ${projectFor(note.projectId)?.name || ""}`.toLowerCase().includes(search.toLowerCase())), [notes, projectId, filter, search, projects]);
  const submit = async (input: { projectId: string; title: string; content: string; type: NoteType; pinned: boolean }) => { await onCreate(input); setCreating(false); };
  return <section className="notes-workspace"><header className="notes-header"><div><span className="notes-icon"><StickyNote size={21} /></span><div><h2>Notes</h2><p>Keep important project context, messages and decisions in one place.</p></div></div><button className="start-btn" onClick={() => setCreating(true)}><Plus size={17} /> New note</button></header><div className="notes-tools"><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search notes…" /></label><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="all">All projects</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></div><div className="notes-filters">{types.map((item) => <button key={item.value} className={filter === item.value ? "active" : ""} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="notes-list">{visible.map((note) => <article className="note-card" key={note.id}><div className="note-card-head"><span className={`note-type ${note.type}`}>{note.type === "important" ? <Star size={13} /> : note.type === "message" ? <MessageSquare size={13} /> : <FileText size={13} />}{note.type}</span><div>{note.pinned && <Pin size={14} />}<button onClick={() => setEditing(note)} aria-label="Edit note"><MoreHorizontal size={18} /></button></div></div><button className="note-card-body" onClick={() => setEditing(note)}><i style={{ background: projectFor(note.projectId)?.color }} /><span><small>{projectFor(note.projectId)?.name || "Project"}</small><h3>{note.title}</h3><p>{note.content}</p></span></button><footer>{note.convertedTaskId ? <span className="note-linked"><CheckSquare size={14} /> Linked task</span> : <button onClick={() => setConverting(note)}><CheckSquare size={14} /> Convert to task</button>}<button onClick={() => void onUpdate(note, { pinned: !note.pinned })}><Pin size={13} /> {note.pinned ? "Unpin" : "Pin"}</button></footer></article>)}</div>{!visible.length && <div className="notes-empty"><StickyNote size={28} /><h3>No notes here</h3><p>Create a project note to keep important context.</p></div>}{(creating || editing) && <NoteEditor note={editing} projects={projects} initialProjectId={projectId === "all" ? undefined : projectId} onClose={() => { setCreating(false); setEditing(null); }} onSave={async (input) => { if (editing) await onUpdate(editing, input); else await submit(input); setEditing(null); }} onArchive={editing ? () => void onUpdate(editing, { state: "archived" }).then(() => setEditing(null)) : undefined} onDelete={editing ? () => void onDelete(editing).then(() => setEditing(null)) : undefined} />}{converting && <ConvertModal note={converting} onClose={() => setConverting(null)} onSave={async (input) => { await onConvert(converting, input); setConverting(null); }} />}</section>;
}
function NoteEditor({ note, projects, initialProjectId, onClose, onSave, onArchive, onDelete }: { note: ProjectNote | null; projects: Project[]; initialProjectId?: string; onClose: () => void; onSave: (input: { projectId: string; title: string; content: string; type: NoteType; pinned: boolean }) => Promise<void>; onArchive?: () => void; onDelete?: () => void }) { const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await onSave({ projectId: String(form.get("projectId")), title: String(form.get("title")), content: String(form.get("content")), type: String(form.get("type")) as NoteType, pinned: form.get("pinned") === "on" }); } finally { setBusy(false); } }; return <div className="modal-backdrop"><form className="note-modal notes-editor" onSubmit={submit}><button className="modal-close" type="button" onClick={onClose}>×</button><div className="modal-icon"><StickyNote size={20} /></div><h3>{note ? "Edit note" : "New note"}</h3><label className="modal-field">PROJECT<select name="projectId" defaultValue={note?.projectId || initialProjectId || ""} required><option value="" disabled>Select project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label className="modal-field">TYPE<select name="type" defaultValue={note?.type || "information"}>{types.filter((item) => !["all", "pinned"].includes(item.value)).map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label className="modal-field">TITLE<input name="title" defaultValue={note?.title || ""} maxLength={160} required /></label><label className="modal-field">DETAILS<textarea name="content" defaultValue={note?.content || ""} maxLength={5000} required /></label><label className="note-pin"><input name="pinned" type="checkbox" defaultChecked={note?.pinned} /> Pin this note</label><div className="modal-actions">{onArchive && <button className="outline-btn" type="button" onClick={onArchive}><Archive size={14} /> Archive</button>}{onDelete && <button className="outline-btn danger-text" type="button" onClick={onDelete}><Trash2 size={14} /> Delete</button>}<button className="start-btn" disabled={busy}>{busy ? "Saving…" : "Save note"}</button></div></form></div>; }
function ConvertModal({ note, onClose, onSave }: { note: ProjectNote; onClose: () => void; onSave: (input: { title: string; priority: TodoPriority; plannedDateString: string }) => Promise<void> }) { const [busy, setBusy] = useState(false); return <div className="modal-backdrop"><form className="note-modal" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await onSave({ title: String(form.get("title")), priority: String(form.get("priority")) as TodoPriority, plannedDateString: String(form.get("plannedDateString")) }); } finally { setBusy(false); } }}><div className="modal-icon"><CheckSquare size={20} /></div><h3>Create task from note</h3><p>The note will stay linked as your source context.</p><label className="modal-field">TASK TITLE<input name="title" defaultValue={note.title} required /></label><label className="modal-field">PRIORITY<select name="priority" defaultValue="medium"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="modal-field">PLAN FOR<input name="plannedDateString" type="date" required /></label><div className="modal-actions"><button className="outline-btn" type="button" onClick={onClose}>Cancel</button><button className="start-btn" disabled={busy}>{busy ? "Creating…" : "Create task"}</button></div></form></div>; }
