import { Copy, Eye, EyeOff, FileUp, KeyRound, Lock, LogOut, Plus, Search, ShieldCheck, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { createVaultMeta, verifyVaultKey } from "../lib/vault-crypto";
import { deleteVaultRecord, decryptVaultRecords, getVaultMeta, newVaultRecordId, saveVaultMeta, saveVaultRecord, subscribeToVaultEnvelopes } from "../lib/vault-service";
import { parseVaultImportFile } from "../lib/vault-import";
import type { Project } from "../types/tracker";
import type { VaultImportSheet, VaultMeta, VaultRecord } from "../types/vault";

type Props = { uid: string; projects: Project[] };
const isSensitive = (key: string) => /pass(word)?|secret|token|api.?key|pin/i.test(key);
const displayTitle = (record: VaultRecord) => record.fields["Site Name"] || record.fields["Site"] || record.fields["Name"] || Object.values(record.fields).find(Boolean) || "Untitled record";

export default function VaultView({ uid, projects }: Props) {
  const [meta, setMeta] = useState<VaultMeta | null | undefined>(undefined); const [key, setKey] = useState<CryptoKey | null>(null); const [records, setRecords] = useState<VaultRecord[]>([]); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [category, setCategory] = useState("all"); const [selected, setSelected] = useState<VaultRecord | null>(null); const [showAdd, setShowAdd] = useState(false); const [showImport, setShowImport] = useState(false); const keyRef = useRef<CryptoKey | null>(null);
  const lock = () => { keyRef.current = null; setKey(null); setRecords([]); setSelected(null); setError(""); };
  useEffect(() => { let active = true; getVaultMeta(uid).then((value) => { if (active) setMeta(value); }).catch(() => { if (active) setError("Vault metadata could not be loaded."); }); return () => { active = false; lock(); }; }, [uid]);
  useEffect(() => { if (!key) return; const unsubscribe = subscribeToVaultEnvelopes(uid, async (items) => { try { const clear = await decryptVaultRecords(uid, key, items); setRecords(clear); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "A Vault record could not be opened."); lock(); } }); return unsubscribe; }, [uid, key]);
  useEffect(() => { if (!key) return; let timeout = 0; const arm = () => { window.clearTimeout(timeout); timeout = window.setTimeout(lock, 5 * 60_000); }; const visibility = () => { if (document.visibilityState === "hidden") lock(); else arm(); }; const events: Array<keyof WindowEventMap> = ["pointerdown", "keydown", "touchstart"]; events.forEach((event) => window.addEventListener(event, arm)); document.addEventListener("visibilitychange", visibility); arm(); return () => { window.clearTimeout(timeout); events.forEach((event) => window.removeEventListener(event, arm)); document.removeEventListener("visibilitychange", visibility); }; }, [key]);
  const unlock = async (password: string, confirmation?: string) => { setError(""); try { let nextKey: CryptoKey; if (!meta) { if (password !== confirmation) throw new Error("Master Password confirmation does not match."); const created = await createVaultMeta(uid, password); await saveVaultMeta(uid, created.meta); nextKey = created.key; setMeta({ ...created.meta, createdAt: null, updatedAt: null }); } else nextKey = await verifyVaultKey(uid, password, meta); keyRef.current = nextKey; setKey(nextKey); } catch (cause) { setError(cause instanceof Error ? cause.message : "Vault could not be unlocked."); } };
  const save = async (input: Omit<VaultRecord, "id" | "createdAt" | "updatedAt">, existing?: VaultRecord) => { if (!keyRef.current) return; const now = Date.now(); const record: VaultRecord = existing ? { ...existing, ...input, updatedAt: now } : { ...input, id: newVaultRecordId(), createdAt: now, updatedAt: now }; await saveVaultRecord(uid, keyRef.current, record); setShowAdd(false); setSelected(record); };
  const categories = [...new Set(records.map((record) => record.category))].sort(); const visible = useMemo(() => records.filter((record) => (category === "all" || record.category === category) && `${record.category} ${Object.entries(record.fields).flat().join(" ")}`.toLowerCase().includes(search.toLowerCase())), [records, category, search]);
  if (meta === undefined) return <section className="vault-workspace"><div className="vault-loading"><ShieldCheck size={30} /> Preparing your encrypted Vault…</div></section>;
  if (!key) return <VaultGate creating={!meta} error={error} onSubmit={unlock} />;
  return <section className="vault-workspace"><header className="vault-header"><div><span className="vault-icon"><ShieldCheck size={22} /></span><div><h2>Password Vault</h2><p>Encrypted on this device before it syncs to Firebase.</p></div></div><div className="vault-header-actions"><button className="outline-btn" onClick={() => setShowImport(true)}><FileUp size={16} /> Import Excel / CSV</button><button className="start-btn" onClick={() => setShowAdd(true)}><Plus size={16} /> Add record</button><button className="outline-btn" onClick={lock}><Lock size={15} /> Lock</button></div></header><div className="vault-security-note"><ShieldCheck size={16} /> Your Master Password and decrypted records are kept only in this browser session.</div><div className="vault-tools"><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search unlocked records…" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></div><div className="vault-layout"><div className="vault-list">{visible.map((record) => <button className={`vault-row ${selected?.id === record.id ? "selected" : ""}`} key={record.id} onClick={() => setSelected(record)}><span><KeyRound size={16} /></span><div><b>{displayTitle(record)}</b><small>{record.category} · {record.projectId ? projects.find((project) => project.id === record.projectId)?.name || "Linked project" : "Private record"}</small></div></button>)}{!visible.length && <div className="vault-empty"><Lock size={26} /><b>No unlocked records found</b><small>Add one manually or import a local Excel/CSV file.</small></div>}</div><div className="vault-detail">{selected ? <VaultDetail record={selected} projects={projects} onDelete={async () => { if (confirm(`Delete “${displayTitle(selected)}”? This cannot be undone.`)) { await deleteVaultRecord(uid, selected.id); setSelected(null); } }} /> : <div className="vault-empty"><ShieldCheck size={30} /><b>Select a record</b><small>Passwords remain hidden until you explicitly reveal them.</small></div>}</div></div>{showAdd && <VaultRecordModal projects={projects} onClose={() => setShowAdd(false)} onSave={save} />}{showImport && <VaultImportModal projects={projects} onClose={() => setShowImport(false)} onImport={async (sheets) => { for (const sheet of sheets) for (const fields of sheet.rows) await save({ category: sheet.category, fields, projectId: null }); setShowImport(false); }} />}</section>;
}

function VaultGate({ creating, error, onSubmit }: { creating: boolean; error: string; onSubmit: (password: string, confirmation?: string) => void }) { const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); return <section className="vault-gate"><div className="vault-gate-card"><span className="vault-icon"><Lock size={26} /></span><h2>{creating ? "Create your Password Vault" : "Unlock your Password Vault"}</h2><p>{creating ? "Choose a Master Password. EA Log never stores it and cannot recover it." : "Enter your Master Password to decrypt your private records on this device."}</p><form onSubmit={(event) => { event.preventDefault(); onSubmit(password, creating ? confirmation : undefined); setPassword(""); setConfirmation(""); }}><label>MASTER PASSWORD<input type="password" value={password} autoComplete={creating ? "new-password" : "current-password"} minLength={14} onChange={(event) => setPassword(event.target.value)} required /></label>{creating && <label>CONFIRM MASTER PASSWORD<input type="password" value={confirmation} autoComplete="new-password" minLength={14} onChange={(event) => setConfirmation(event.target.value)} required /></label>}{error && <p className="vault-error">{error}</p>}<button className="start-btn" type="submit"><Lock size={16} /> {creating ? "Create encrypted Vault" : "Unlock Vault"}</button></form><small><ShieldCheck size={14} /> The password is never uploaded. Forgetting it means the Vault cannot be recovered.</small></div></section>; }
function VaultDetail({ record, projects, onDelete }: { record: VaultRecord; projects: Project[]; onDelete: () => Promise<void> }) { const [revealed, setRevealed] = useState<string | null>(null); const [copied, setCopied] = useState(""); const copy = async (label: string, value: string) => { await navigator.clipboard.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1500); }; return <div className="vault-detail-content"><header><div><small>{record.category}</small><h3>{displayTitle(record)}</h3></div><button className="icon-btn danger-text" onClick={() => void onDelete()} aria-label="Delete record"><Trash2 size={17} /></button></header>{Object.entries(record.fields).map(([label, value]) => { const sensitive = isSensitive(label); const visible = !sensitive || revealed === label; return <div className="vault-field" key={label}><small>{label}</small><div><code>{visible ? value || "—" : "••••••••••••"}</code>{sensitive && <button className="icon-btn" onClick={() => setRevealed(visible ? null : label)} aria-label={visible ? "Hide value" : "Reveal value"}>{visible ? <EyeOff size={15} /> : <Eye size={15} />}</button>}<button className="icon-btn" onClick={() => void copy(label, value)} aria-label={`Copy ${label}`}><Copy size={15} /></button></div>{copied === label && <em>Copied to system clipboard</em>}</div>})}<footer>{record.projectId && <span>Linked to {projects.find((project) => project.id === record.projectId)?.name || "project"}</span>}<span>Updated {new Date(record.updatedAt).toLocaleDateString()}</span></footer></div>; }
function VaultRecordModal({ projects, onClose, onSave }: { projects: Project[]; onClose: () => void; onSave: (input: Omit<VaultRecord, "id" | "createdAt" | "updatedAt">) => Promise<void> }) { const [fields, setFields] = useState<Array<[string, string]>>([["Site Name", ""], ["Username / Email", ""], ["Password", ""], ["URL", ""], ["Notes", ""]]); const [busy, setBusy] = useState(false); return <div className="modal-backdrop"><form className="note-modal vault-record-modal" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await onSave({ category: String(form.get("category")).trim() || "General", projectId: String(form.get("projectId")) || null, fields: Object.fromEntries(fields.filter(([label]) => label.trim()).map(([label, value]) => [label.trim(), value])) }); } finally { setBusy(false); } }}><button className="modal-close" type="button" onClick={onClose}>×</button><div className="modal-icon"><KeyRound size={20} /></div><h3>Add encrypted record</h3><label className="modal-field">CATEGORY<input name="category" defaultValue="General" required /></label><label className="modal-field">LINK PROJECT (OPTIONAL)<select name="projectId" defaultValue=""><option value="">No project link</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><div className="vault-field-editor">{fields.map(([label, value], index) => <div key={index}><input aria-label="Field name" value={label} onChange={(event) => setFields((current) => current.map((item, itemIndex) => itemIndex === index ? [event.target.value, item[1]] : item))} placeholder="Field name" /><input aria-label={`${label || "Field"} value`} type={isSensitive(label) ? "password" : "text"} value={value} onChange={(event) => setFields((current) => current.map((item, itemIndex) => itemIndex === index ? [item[0], event.target.value] : item))} placeholder="Value" /><button className="icon-btn" type="button" onClick={() => setFields((current) => current.filter((_, itemIndex) => itemIndex !== index))} aria-label="Remove field"><X size={15} /></button></div>)}<button className="text-btn" type="button" onClick={() => setFields((current) => [...current, ["", ""]])}><Plus size={14} /> Add field</button></div><div className="modal-actions"><button className="outline-btn" type="button" onClick={onClose}>Cancel</button><button className="start-btn" disabled={busy}>{busy ? "Encrypting…" : "Save encrypted record"}</button></div></form></div>; }
function VaultImportModal({ projects, onClose, onImport }: { projects: Project[]; onClose: () => void; onImport: (sheets: VaultImportSheet[]) => Promise<void> }) { const [sheets, setSheets] = useState<VaultImportSheet[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); return <div className="modal-backdrop"><div className="note-modal vault-import-modal"><button className="modal-close" onClick={onClose}>×</button><div className="modal-icon"><FileUp size={20} /></div><h3>Import Excel / CSV</h3><p>Headers and values are processed locally, then encrypted before sync.</p><label className="vault-file-input">Choose .xlsx or CSV<input type="file" accept=".xlsx,.csv,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setError(""); setSheets(await parseVaultImportFile(file)); } catch (cause) { setSheets([]); setError(cause instanceof Error ? cause.message : "Import could not be read."); } }} /></label>{sheets.map((sheet, index) => <div className="vault-import-sheet" key={`${sheet.category}-${index}`}><input value={sheet.category} onChange={(event) => setSheets((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, category: event.target.value } : item))} /><span>{sheet.rows.length} records · {sheet.headers.join(" · ")}</span></div>)}{error && <p className="vault-error">{error}</p>}<div className="modal-actions"><button className="outline-btn" onClick={onClose}>Cancel</button><button className="start-btn" disabled={!sheets.length || busy} onClick={async () => { setBusy(true); try { await onImport(sheets); } finally { setBusy(false); } }}>{busy ? "Encrypting…" : `Import ${sheets.reduce((total, sheet) => total + sheet.rows.length, 0)} records`}</button></div></div></div>; }
